修正部分内容
TeamFlos/phira-docs pull request #25
Opened 2024-11-08 16:18 UTC by 2278535805

2024-11-08 22:20 UTC, NuanRMxi requested changes
除了 `offset` 类型的更正、`note` 的 `time` 的类型的更正以及对 `start` `end` `start2` `end2`的描述更改，其他均为错误，请更正

2024-11-08 22:20 UTC, NuanRMxi commented on src/chart-standard/chart-format/phi/note.md
holdTime有误，谱面文件中holdTime的值含有小数点。

2024-11-08 22:20 UTC, NuanRMxi commented on src/chart-standard/chart-format/phi/event.md
什么是 `intt`，时间单位为 `float` 无误，并非 `int`。

2024-11-09 00:06 UTC, qaqFei commented on src/chart-standard/chart-format/phi/event.md
time都是int?  好像是float吧

2024-11-09 00:06 UTC, qaqFei commented on src/chart-standard/chart-format/phi/note.md
`note初始化时距离判定线的高度`与`note打击时判定线流过的速度`  意思相同

2024-11-09 00:07 UTC, NuanRMxi commented on src/chart-standard/chart-format/phi/event.md
![image](https://github.com/user-attachments/assets/0f54fecf-2e05-4679-8d06-494e40357961)

2024-11-09 00:08 UTC, NuanRMxi commented on src/chart-standard/chart-format/phi/event.md
![image](https://github.com/user-attachments/assets/7091461d-f538-46c9-a5a2-a227164b131f)

2024-11-09 00:09 UTC, NuanRMxi commented on src/chart-standard/chart-format/phi/event.md
`note` 的 `time` 是 `int` ，事件的 `time` 是 `float`

2024-11-09 02:36 UTC, 2278535805 commented
已修改

2024-11-09 02:40 UTC, merged

2024-11-09 02:41 UTC, NuanRMxi commented
感谢您的修正。